### ISSUE TITLE
Question about the calculation of MSE.

### ISSUE THREAD

**Issue by Dangzheng** [WangYueFt/dcp#10]
Hi Yue, 

Many thanks for the great work. I have a question about the calculation of the MSE. When calculating the MSE, we should have already got the 1-to-1 correspondence between two point cloud sets. But in the following line, the order of point has been permuted. 
https://github.com/WangYueFt/dcp/blob/213d573eb182b2788913ab5befd4f14ded38526a/data.py#L118
The 1-to-1 correspondence relationship would be broken. If I understand correctly, as a result, in the testing time, the MSE could never reach zero. I was wondering if this is a bug or I missed something in the code.

Bests,
Zheng

**Comment by WangYueFt** [comment]
> Hi Yue,
> 
> Many thanks for the great work. I have a question about the calculation of the MSE. When calculating the MSE, we should have already got the 1-to-1 correspondence between two point cloud sets. But in the following line, the order of point has been permuted.
> https://github.com/WangYueFt/dcp/blob/213d573eb182b2788913ab5befd4f14ded38526a/data.py#L118
> 
> 
> The 1-to-1 correspondence relationship would be broken. If I understand correctly, as a result, in the testing time, the MSE could never reach zero. I was wondering if this is a bug or I missed something in the code.
> Bests,
> Zheng

Hi Zheng,

Thanks for asking. Yes, the 1-to-1 correspondence is broken, so we don't use the MSE between points as a metric. We only report metrics on R, t. 

Best,
Yue
