### ISSUE TITLE
Questions related to the performance of DCP and ICP

### ISSUE THREAD

**Issue by XuyangBai** [WangYueFt/dcp#15]
Hi @WangYueFt  Thanks for your sharing. I have several questions related to the paper:
1. For the performance of ICP reported in your paper, I wonder what is the initial transformation you used for ICP algorithm?
2. It looks like your method does not need an initial transformation as input, so have you ever test your model on larger rotation and translation cases? ( like rotation in [0, 360degree) translation in [-1, 1]?)
3. Will your model handle the cases where there is no 1-to-1 correspondence? I think for the current experiment setting,  all the point cloud pairs have 1-to-1 correspondence. How about two point clouds have different number of points?

Best,
Xuyang.

**Comment by WangYueFt** [comment]
> Hi @WangYueFt Thanks for your sharing. I have several questions related to the paper:
> 
> 1. For the performance of ICP reported in your paper, I wonder what is the initial transformation you used for ICP algorithm?
> 2. It looks like your method does not need an initial transformation as input, so have you ever test your model on larger rotation and translation cases? ( like rotation in [0, 360degree) translation in [-1, 1]?)
> 3. Will your model handle the cases where there is no 1-to-1 correspondence? I think for the current experiment setting,  all the point cloud pairs have 1-to-1 correspondence. How about two point clouds have different number of points?
> 
> Best,
> Xuyang.

Hi Xuyang,

To answer your questions,

1. We use random initialization, so you can image the ICP would fail every case. 
2. We tested a larger rotation in [0, 180] but not in [0, 360]. It still works well.
3. Yes, the non 1-to-1 correspondence case is tricky for DCP. We have a follow-up paper on how to address this: http://papers.nips.cc/paper/9085-prnet-self-supervised-learning-for-partial-to-partial-registration

**Comment by qiaozhijian** [comment]
> > Hi @WangYueFt Thanks for your sharing. I have several questions related to the paper:
> > 
> > 1. For the performance of ICP reported in your paper, I wonder what is the initial transformation you used for ICP algorithm?
> > 2. It looks like your method does not need an initial transformation as input, so have you ever test your model on larger rotation and translation cases? ( like rotation in [0, 360degree) translation in [-1, 1]?)
> > 3. Will your model handle the cases where there is no 1-to-1 correspondence? I think for the current experiment setting,  all the point cloud pairs have 1-to-1 correspondence. How about two point clouds have different number of points?
> > 
> > Best,
> > Xuyang.
> 
> Hi Xuyang,
> 
> To answer your questions,
> 
>     1. We use random initialization, so you can image the ICP would fail every case.
> 
>     2. We tested a larger rotation in [0, 180] but not in [0, 360]. It still works well.
> 
>     3. Yes, the non 1-to-1 correspondence case is tricky for DCP. We have a follow-up paper on how to address this: http://papers.nips.cc/paper/9085-prnet-self-supervised-learning-for-partial-to-partial-registration
Hello!
For your discussion, I did some experiments.
1. I set rotation [0,45degree], and translation [-0.5,0.5]. But ICP never fails.
2.I tested a larger rotation in [0, 180] using dcp_v2.t7 trained on [0,45degree], but it didn't work well.
But ICP often fails when rotation is in [0,180degree]
