### ISSUE TITLE
typo in the title of readme: Deep **Cloeset** Point.

### ISSUE THREAD

**Issue by VictorZuanazzi** [WangYueFt/dcp#16]
Not really an issue, just a friendly review: there is a typo in the title of readme: Deep **Cloeset** Point.

=)

**Comment by WangYueFt** [comment]
> Not really an issue, just a friendly review: there is a typo in the title of readme: Deep **Cloeset** Point.
> 
> =)

Thanks so much for the good catch! I've just fixed the typo.
