### ISSUE TITLE
Hello, I a question in paper

### ISSUE THREAD

**Issue by BlankCheng** [WangYueFt/dcp#2]
```
 scores = torch.matmul(src_embedding.transpose(2, 1).contiguous(), tgt_embedding) / math.sqrt(d_k)
 scores = torch.softmax(scores, dim=2)
 src_corr = torch.matmul(tgt, scores.transpose(2, 1).contiguous())
```
I am confused why muplying target by scores, why not just use target cloud as the src_corr?

**Comment by WangYueFt** [comment]
> ```
>  scores = torch.matmul(src_embedding.transpose(2, 1).contiguous(), tgt_embedding) / math.sqrt(d_k)
>  scores = torch.softmax(scores, dim=2)
>  src_corr = torch.matmul(tgt, scores.transpose(2, 1).contiguous())
> ```
> 
> I am confused why muplying target by scores, why not just use target cloud as the src_corr?

Hi,

For general point cloud to point cloud registration, we don't know the correspondences between the source point cloud and target point cloud. The scores here is a correspondence a matrix.

Best,
Yue
