### ISSUE TITLE
What license is the code released under?

### ISSUE THREAD

**Issue by AndreiBarsan** [WangYueFt/dcp#3]
Dear DCP authors,

Is there a specific license under which the code is released? The repository currently doesn't specify one.

Thank you,
Andrei

**Comment by WangYueFt** [comment]
> Dear DCP authors,
> 
> Is there a specific license under which the code is released? The repository currently doesn't specify one.
> 
> Thank you,
> Andrei

Hi Andrei,

We use MIT license and will update the repo very soon.

Best,
Yue

**Comment by AndreiBarsan** [comment]
Dear Yue,

Thanks for your fast reply. That's fantastic news, thank you very much!!

Best,
Andrei
