### ISSUE TITLE
not works well given incomplete point cloud

### ISSUE THREAD

**Issue by BlankCheng** [WangYueFt/dcp#4]
Hi, sorry to bother.  When I test it with a model cloud as a souce and a transformed cloud(by random rotation and translation) as target, it works amazingly. 
But when I use a incomplete  point cloud(a RGBD projection to 3D, incomplete here is point cloud from one perspective) as source and a complete model in the RGBD, it works poorly.  I wonder it is my mistaken operation or the model itself? Will it perform as perfectly as it is on complete ones now if I train it with incomplete point cloud?
Thanks!
Best 
Cheng

**Comment by zhangshabao** [comment]
Excuse me, I would like to ask you how to test your own code?
Thanks!

**Comment by zhangshabao** [comment]
Excuse me, I would like to ask you how to test your own code?

**Comment by WangYueFt** [comment]
> Hi, sorry to bother. When I test it with a model cloud as a souce and a transformed cloud(by random rotation and translation) as target, it works amazingly.
> But when I use a incomplete point cloud(a RGBD projection to 3D, incomplete here is point cloud from one perspective) as source and a complete model in the RGBD, it works poorly. I wonder it is my mistaken operation or the model itself? Will it perform as perfectly as it is on complete ones now if I train it with incomplete point cloud?
> Thanks!
> Best
> Cheng

Hi Cheng,

Yes. There is a gap between the training and testing. If you use the pretrained model, which is trained on ModelNet40, it's highly likely to fail on scans. I would suggest training on the data you collect, and then testing. We're also working on partial point cloud matching, stay tuned. :-)

Best,
Yue

**Comment by BlankCheng** [comment]
Many thanks! I'll try it!

**Comment by joy-yjl** [comment]
> Many thanks! I'll try it!

can you tell me how the networl perform on  incomplete point cloud?
