### ISSUE TITLE
code speed problem

### ISSUE THREAD

**Issue by zhangshabao** [WangYueFt/dcp#6]
I tested the code with my data. The running time was 4s, the computer was 1070, and the video memory was 8 gigabytes.What is wrong?Excluding the read data time, the network runs in 2. 2 seconds

**Comment by WangYueFt** [comment]
> I tested the code with my data. The running time was 4s, the computer was 1070, and the video memory was 8 gigabytes.What is wrong?Excluding the read data time, the network runs in 2. 2 seconds

Hi,

If you're using your own data, the problem can be: 1. your point clouds are big; 2. data loading seems slow (it takes 1.8s?).

Best,
Yue

**Comment by zhangshabao** [comment]
> 
> 
> > I tested the code with my data. The running time was 4s, the computer was 1070, and the video memory was 8 gigabytes.What is wrong?Excluding the read data time, the network runs in 2. 2 seconds
> 
> Hi,
> 
> If you're using your own data, the problem can be: 1. your point clouds are big; 2. data loading seems slow (it takes 1.8s?).
> 
> Best,
> Yue

emmmm The number of point clouds is about 1w, and the speed of reading point clouds accounts for 1.8s.I use TXT file to read。 There have a good way to read?

**Comment by cbenitez81** [comment]
One way to do it, it's maybe to precompute the neighbors using a kd-tree, and modify the database to have this at hand for each epoch. knn complexity it's n^2, so if your cloud is big, the implementation in python can take a while. Open3d has an efficient implementation
