### ISSUE TITLE
Question about point cloud sampling strategy

### ISSUE THREAD

**Issue by Ryan-Zirui-Wang** [WangYueFt/dcp#8]
Hi Yue,

Many thanks for the great work. I have a question about the point cloud sampling strategy in your code. If I understand your code correctly, the point cloud sampling is done before creating ground truth, does that mean the point cloud X and point cloud Y have a 1-to-1 correspondence? i.e. if a perfect R and t are computed, X and Y will have an exact alignment? 

More specifically, say we have a point cloud before sampling **A**, from what I understanding, you sample it to get **B,** and transform **B** to **C** using a ground truth transformation **T** and you train it with **B,** **C,** and **T.**

I was wondering have you ever done any experiment that adding ground truth transformation before sampling and how does the NN perform? That means apply ground truth transformation **T** over **A** to have **D,** sample **A** to have **E,** sample **D** to have **F** and train the NN with **E,** **F,** and **T.**

Best,
Zirui

**Comment by WangYueFt** [comment]
Hi Zirui,

Thanks for pointing it out. It's a great question. 

Your understanding is correct: in the current setup, the two point clouds have 1-to-1 correspondence. We have an ongoing project testing how it works in the case you suggested. 

Best,
Yue

**Comment by Ryan-Zirui-Wang** [comment]
Hi Yue,

Thanks a lot for your prompt reply and looking forward to your future work. Btw, hope you don't mind me asking, is this paper accepted by any conference so I can cite it in my current work? or I should just use the Arxiv version?

Best,
Zirui
